apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantum-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quantum-service
  template:
    metadata:
      labels:
        app: quantum-service
    spec:
      containers:
      - name: quantum-service-container
        image: SAMPLE_DOCKER_IMAGE:SAMPLE_DOCKER_TAG
        ports:
        - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: quantum-service
spec:
  type: NodePort
  selector:
    app: quantum-service
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 5050
    nodePort: SAMPLE_KUBERNETES_NODEPORT
